spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TestDb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # проверяет таблицы, созданные Liquibase
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/changeset/changelog-master.yml